#Spring≈‰÷√
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm_db?serverTimezone=UTC&useSSL=false
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
#MyBatis≈‰÷√
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test.bean

#∂Àø⁄∫≈≈‰÷√
server:
  port: 80